# Generated by Django 4.0.3 on 2022-04-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_fooditem_measure'),
        ('recipes', '0003_step_food_items'),
    ]

    operations = [
    ]
