# Generated by Django 4.0.3 on 2022-04-25 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_step_food_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="amount",
            field=models.FloatField(
                validators=[django.core.validators.MaxValueValidator(20)]
            ),
        ),
    ]
